import Head from "next/head";
import { useState } from "react";
import GameDetail from "../components/GameDetail";
import GameList from "../components/GameList";
import GameListType from "../components/GameListType";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [idType, setIdType] = useState(0);
  const [gameDescription, setGameDescription] = useState({});
  const [display, setDisplay] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <GameListType setIdType={setIdType} setDisplay={setDisplay}/>
        {
          display? <GameDetail gameDescription={gameDescription} setDisplay={setDisplay}/> : <GameList idType={idType} setDisplay={setDisplay} setGameDescription={setGameDescription}/> 
        }
        
      </main> 
    </div> 
  );
}
