import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import GameDetail from "../components/GameDetail";
import GameList from "../components/GameList";
import GameListType from "../components/GameListType";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [idType, setIdType] = useState(0);
  const [gameDescription, setGameDescription] = useState({});
  const [display, setDisplay] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.eevee}>

        <Image
          
          src="/eevee.gif"
          height="60"
          width="120"
        />
        </div>
        <h1 className={styles.h1}>Stime</h1>
        <div className={styles.divContent}>
          <div className={styles.div}>
            <Image
              src="/toudoudou.png"
              height="80"
              width="80"
              className={styles.img}
            />
          </div>
        </div>
      </header>
      { <main className={styles.main}>
        <GameListType setIdType={setIdType} setDisplay={setDisplay} />
        {display ? (
          <GameDetail
            gameDescription={gameDescription}
            setDisplay={setDisplay}
          />
        ) : (
          <GameList
            idType={idType}
            setDisplay={setDisplay}
            setGameDescription={setGameDescription}
          />
        )}
      </main> }
    </div>
  );
}
